services:

  redis:
    image: redis
    ports:
      - "6379"

  consul:
    image: consul
    ports:
      - "8500:8500"

  vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: someRoot
    ports:
      - "8200:8200"

  mockservice:
    image: testproject/mockservice:1.0
    build:
      dockerfile: .\MockService\Dockerfile
    depends_on:
      - redis
      - consul
    ports:
      - "5296:80"

  webapi:
    image: testproject/webapi:1.0
    build:
      dockerfile: .\WebApi\Dockerfile
    depends_on:
      - redis
      - consul
      - mockservice
    ports:
      - "5194:80"

