services:

  redis:
    image: redis
    ports:
      - "6379"

  consul:
    image: consul
    ports:
      - "8500:8500"

  vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: someRoot
    ports:
      - "8200:8200"

  vaultservice:
    build:
      context: .
      dockerfile: .\VaultService\Dockerfile
    depends_on:
      - consul
      - vault
    ports:
      - "5080:80"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  mockservice:
    build:
      context: .
      dockerfile: .\MockService\Dockerfile
    depends_on:
      - redis
      - consul
      - zipkin
    ports:
      - "5296:80"

  webapi:
    build:
      context: .
      dockerfile: .\WebApi\Dockerfile
    depends_on:
      - redis
      - consul
      - mockservice
      - zipkin
    ports:
      - "5194:80"

  ocelotgw:
    build: 
      context: .
      dockerfile: .\OcelotApiGw\Dockerfile
    ports:
      - "5175:80"

  ssoservice:
    build:
      context: .
      dockerfile: .\SSOService\Dockerfile
    ports:
      - "5065:80"

  logstash:
    image: logstash:8.2.2
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch

  elasticsearch:
   image: elasticsearch:8.2.2
   ports:
    - 9200:9200

  kibana:
   image: kibana:8.2.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200   

